# Generated by Django 5.2.13 on 2026-04-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(max_length=64, unique=True, verbose_name="Kalit"),
                ),
                ("value", models.TextField(blank=True, verbose_name="Qiymat")),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="Izoh"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
            ],
            options={
                "verbose_name": "Sayt sozlamasi",
                "verbose_name_plural": "Sayt sozlamalari",
                "ordering": ["key"],
            },
        ),
    ]
