# Generated by Django 5.2.13 on 2026-04-08 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kinoteatr nomi')),
                ('location', models.CharField(max_length=300, verbose_name='Joylashgan joyi')),
                ('city', models.CharField(max_length=100, verbose_name='Shahar')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('address', models.CharField(max_length=300, verbose_name='Manzil')),
            ],
            options={
                'verbose_name': 'Kinoteatr',
                'verbose_name_plural': 'Kinoteatrlar',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Film nomi')),
                ('description', models.TextField(verbose_name='Tavsifi')),
                ('genre', models.CharField(max_length=100, verbose_name='Janri')),
                ('duration', models.IntegerField(verbose_name='Davomiyligi (minutlarda)')),
                ('rating', models.FloatField(default=0, verbose_name='Reytingi')),
                ('poster_url', models.URLField(blank=True, verbose_name='Poster rasm')),
                ('trailer_url', models.URLField(blank=True, verbose_name='Trailer URL')),
                ('release_date', models.DateField(verbose_name='Chiqarilish sanasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Filmlar',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Zal nomi')),
                ('hall_type', models.CharField(choices=[('standard', 'Standard'), ('imax', 'IMAX'), ('3d', '3D')], max_length=20, verbose_name='Zal turi')),
                ('total_seats', models.IntegerField(verbose_name="Umumiy o'rindiqlar soni")),
                ('rows', models.IntegerField(default=10, verbose_name='Qatorlar soni')),
                ('columns', models.IntegerField(default=12, verbose_name='Ustunlar soni')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='cinema.cinema', verbose_name='Kinoteatr')),
            ],
            options={
                'verbose_name': 'Zal',
                'verbose_name_plural': 'Zallar',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=2, verbose_name='Qator')),
                ('number', models.IntegerField(verbose_name='Raqami')),
                ('seat_type', models.CharField(choices=[('regular', 'Oddiy'), ('vip', 'VIP'), ('couple', 'Juftlik')], default='regular', max_length=20, verbose_name="O'rindiq turi")),
                ('is_available', models.BooleanField(default=True, verbose_name='Mavjud')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Narxi')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='cinema.hall', verbose_name='Zal')),
            ],
            options={
                'verbose_name': "O'rindiq",
                'verbose_name_plural': "O'rindiqlar",
                'unique_together': {('hall', 'row', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('ticket_price', models.DecimalField(decimal_places=2, default=45000, max_digits=10, verbose_name='Chipta narxi')),
                ('available_seats', models.IntegerField(verbose_name="Mavjud o'rindiqlar")),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='cinema.hall', verbose_name='Zal')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='cinema.movie', verbose_name='Film')),
            ],
            options={
                'verbose_name': 'Seans',
                'verbose_name_plural': 'Seanslar',
                'ordering': ['start_time'],
                'unique_together': {('hall', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('cancelled', 'Bekor qilinga'), ('completed', 'Yakunlangan')], default='pending', max_length=20, verbose_name='Holati')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy narx')),
                ('number_of_seats', models.IntegerField(verbose_name="O'rindiqlar soni")),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Broniya sanasi')),
                ('booking_reference', models.CharField(max_length=20, unique=True, verbose_name='Broniya raqami')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cinema.showtime', verbose_name='Seans')),
            ],
            options={
                'verbose_name': 'Broniya',
                'verbose_name_plural': 'Broniyalar',
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50, unique=True, verbose_name='Chipta raqami')),
                ('qr_code', models.TextField(blank=True, verbose_name='QR kod')),
                ('is_used', models.BooleanField(default=False, verbose_name="Ishlatilib bo'ldi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='cinema.booking', verbose_name='Broniya')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.seat', verbose_name="O'rindiq")),
            ],
            options={
                'verbose_name': 'Chipta',
                'verbose_name_plural': 'Chiptalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Matn')),
                ('completed', models.BooleanField(default=False, verbose_name='Yakunlangan')),
                ('priority', models.CharField(choices=[('low', 'Kam'), ('normal', 'Normal'), ('high', 'Muhim')], default='normal', max_length=10, verbose_name='Muhimlik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Bajarilish sanasi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "To'do",
                'verbose_name_plural': "To'dolar",
                'ordering': ['-created_at'],
            },
        ),
    ]
