# Generated by Django 5.2.13 on 2026-04-08 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_movie_poster_alter_movie_poster_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL slugi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsifi')),
                ('icon', models.CharField(default='movie', max_length=50, verbose_name='Ikonka (Material Icons)')),
                ('color', models.CharField(default='#4b8eff', max_length=7, verbose_name='Rang (Hex)')),
                ('order', models.IntegerField(default=0, verbose_name='Tartibi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='cinema.category', verbose_name='Kategoriya'),
        ),
    ]
