# Generated by Django 5.2.13 on 2026-04-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_category_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='total_seats',
            field=models.IntegerField(blank=True, default=0, verbose_name="Umumiy o'rindiqlar soni"),
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
